[package]
name = "mesh_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
vek = "0.17.1"
tokio = { version = "1.41.1", features = ["full"] }
serde = "1.0.215"
bincode = "1.3.3"
futures = "0.3.31"
